:Title: OGC (Data Retrieval Pattern API SWG Charter)
:titletext: {Title}
:doctype: book
:encoding: utf-8
:lang: en
:toc:
:toc-placement!:
:toclevels: 4
:numbered:
:sectanchors:
:source-highlighter: pygments

<<<
[cols = ">",frame = "none",grid = "none"]
|===
|{set:cellbgcolor:#FFFFFF}
|[big]*Open Geospatial Consortium*
|Submission Date: <2019-08-21>
|Approval Date:   <yyyy-mm-dd>
|Internal reference number of this OGC(R) document:    19-055r0
|Category: OGC(R) Standards Working Group Charter
|Authors:   Chris Little, Steve Olson, Frédéric Guillaud
|===

[cols = "^", frame = "none"]
|===
|[big]*{titletext}*
|===

[cols = "^", frame = "none", grid = "none"]
|===
|*Copyright notice*
|Copyright (C) 2019 Open Geospatial Consortium
|To obtain additional rights of use, visit http://www.opengeospatial.org/legal/
|===

<<<

////
Version of 2018-12-12
Some Instructions
This document is the template to be used for proposing the formation of a new Standards Working Group (SWG).

The first step is to complete the SWG Charter for the proposed new SWG.

The next step is to email the draft SWG charter to the Technical Committee Chair (TCC).  The TCC will review the draft charter and make any necessary comments and provide guidance.

Finally, once the Charter is ready, the SWG charter will be posted to the OGC Pending Documents and the vote process in the Technical Committee Policies and Procedures will start.

Any questions, please contact OGC staff.
////

To: OGC members & interested parties

A new OGC Standards Working Group is being formed. The OGC members listed below have proposed the OGC Data Pattern Retrieval API SWG.  The SWG proposal provided in this document meets the requirements of the OGC Technical Committee (TC) Policies and Procedures.

The SWG name, statement of purpose, scope, list of deliverables, audience, and language specified in the proposal will constitute the SWG's official charter. Technical discussions may occur no sooner than the SWG's first meeting.

This SWG will operate under the OGC IPR Policy. The eligibility requirements for becoming a participant in the SWG at the first meeting (see details below) are that:

* You must be an employee of an OGC member organization or an individual
member of OGC;

* The OGC member must have signed the OGC Membership agreement;

* You must notify the SWG chair of your intent to participate to the first meeting. Members may do so by logging onto the OGC Portal and navigating to the Observer page and clicking on the link for the SWG they wish to join and;

* You must attend meetings of the SWG. The first meeting of this SWG is at the time and date fixed below. Attendance may be by teleconference.

Of course, participants also may join the SWG at any time. The OGC and the SWG welcomes all interested parties.

Non-OGC members who wish to participate may contact us about joining the OGC. In addition, the public may access some of the resources maintained for each SWG: the SWG public description, the SWG Charter, Change Requests, and public comments, which will be linked from the SWG’s page.

Please feel free to forward this announcement to any other appropriate lists. The OGC is an open standards organization; we encourage your feedback.

== Purpose of the Standards Working Group

The Data Retrieval Pattern API Standards Working Group will standardise some APIs, defined with OpenAPI Version 3, to retrieve various commmon data patterns from a data cube. The data patterns will include, but are not restricted to, data at a point in space and time, time series at a point, data along a trajectory, which may be 2, 3, or 4 dimensional, and covering a specified polygon or rectangular tile.  

== Business Value Proposition

Much environmental data is truly 'Big Data', in that it cannot be readily copied and distributed in sensible timescales for many uses. By specifying precisely just the data required in a convenient pattern familiar to the user, a service provider can extract and serve the requested data, simplying access for the user, and hiding the service implementation details, while being scaleable both in terms of the underlying data cube volume and the number of supported simultaneous users. 

By using stable, standardised, service APIs based on simple data retrieval patterns, it is envisaged that access and use of data and information will be enabled in different domains, including geospatial, enabling more innovation and value.

It is envisaged that the standard will be consistent with the strategic direction established by Web Feature Service Version 3 and the future OWS Common for Web Services.

The service APIs will support both traditional and cloud-based approaches to computing and also enable a mix of public and private business models on a 'level playing field'. For example, no one country is capable of supplying weather forecast data at the highest useful resolutions for the whole globe, so a distributed scalable approach is essential, enabling both advanced countries and the Least Developed Countries contribute to global strategic intiatives of sustainability and development.

== Scope of Work

The original requirements for this standard were evolved in the Met Ocean Domain Working Group, but it is envisaged that many of the common data patterns are applicable in other environmental sciences, or even other domains. The data retrieval patterns to access weather and climate data have been stable for many years. Such patterns include, but are not restricted to, point data, time-series at a point, vertical profiles, trajectories (whether in 2, 3 or 4 dimensions), polygons, or rectangular tiles.

There are two main use cases: 

1. An end user requires some convenient data for a specific, familiar purpose, such as a forecast surface temperature at a point or over an area, or wind speed and direction along a proposed trajectory or route, but the user does not need the full range of data that modern weather or climate predictions, or other Big Data systems, engender.

2. A service provider of many value-added products and information services needs an architecture that decouples the provision of data to many evolving distributed applications from the underlying stable, operational, centrallised bulk data production systems. 

The underlying bulk 'data cube' may be based on regular calculation grids, or may be point-cloud observation based, or other structures.

=== Statement of relationship of planned work to the current OGC standards baseline

There is no OGC standard addressing these requirements.

It is proposed to use the OpenAPI Version 3 framework to define the APIs, which is consistent with the OGC WFS3. Previous experiments, proof-of-concepts and prototyping work have confirmed the feasibility of a consistent approach. 

It is planned that once the SWG is established, a candidate standard will be developed within one year.

=== What is Out of Scope?

The SWG will only standardise data retrieval orientated APIs, not product-based APIs that need business specific logic and rules.

Initially, the SWG will not standardise any data patterns other than: point, timeseries, vertical profile, trajectory, corridor, polygon or rectangular tile.

=== Specific Existing Work Used as Starting Point

The SWG work is based on:

1. The Met Ocean Domain WG work to specify various Best Practices;

2. The WCS Met Ocean Application profiles done in the WCS SWG;

3. A Met Ocean DWG Hackathon held in December 2018 in Washington DC, USA;

4. The OGC Hackathon held in June 2019 in London, England, UK;

5. The Weather on the Web API Engineering Report.

=== Is This a Persistent SWG

[x] YES

[ ] NO

=== When can the SWG be Inactivated

As there are several data pattern APIs to be standardised, Persistent SWG status is proposed, but when all the initial deliverables are finished, inactivation will be considered.

== Description of deliverables

////
This section describes what the deliverables will be for this SWG activity. Deliverables could be a revision to an existing standard, including revisions to schemas. A deliverable could also be a best practices document.

This section also includes a preliminary schedule of activities. For example, an RFC focused SWG schedule would provide a plan and schedule that includes the start date, target date for release of the candidate standard for public review, date for consolidation of comments, date for edits to document based on comments, and a final target date for making a recommendation to the Membership. This information will be made public and will also be used as input to a RoadMap for the document. Therefore, the more detail the better.
////

=== Initial Deliverables

////
Describe the initial standard(s) to be developed by the SWG.
////

=== Additional SWG Tasks

////
Describe each additional standard to be developed by the SWG as an additional task after the deliverables from the initial charter have been completed. This section is blank in a new charter, then is populated with each task approval request per the OGC TC Policies and Procedures.
////

== IPR Policy for this SWG

[x] RAND-Royalty Free

[ ] RAND for fee

== Anticipated Audience / Participants

////
Description of the target participants in this SWG. For example, if the SWG were focused on a candidate spatial query language standard: Those involved in the design, development, implementation, or use of elements listed above in "Scope of the Work".  This includes search service providers, prospective users of search services exposed as XML, information architects and bibliographic, metadata, and content provider.

This is not meant as a limiting statement but instead is intended to provide guidance to interested potential participants as to whether they wish to participate in this SWG.
////

== Domain Working Group Endorsement

////
The SWG will list all Domain Working Groups (DWGs) in which the SWG formation was discussed and/or chartered. If a DWG has specifically endorsed the formation of the SWG, then a statement of endorsement should be included.
////

The Met Ocean DWG discussed and endorses the establishment of this SWG.

== Other informative information about the work of this SWG

=== Collaboration

////
Describe the work environment of the SWG, including the use of GitHub or GitLab.
////

=== Similar or Applicable Standards Work (OGC and Elsewhere)

////
The following standards and projects may be relevant to the SWG's planned work, although none currently provide the functionality anticipated by this committee's deliverables:

OASIS BPEL
IETF HTTP

The SWG intends to seek and if possible maintain liaison with each of the organizations maintaining the above works.
////

=== Details of first meeting

////
Example:
The first meeting of the SWG will be held by telephone conference call at 10AM EDT on 1 October 2007. Call-in information will be provided to the SWG's e-mail list and on the portal calendar in advance of the meeting.
////

=== Projected on-going meeting schedule

////
Example:
The work of the SWG will be carried out primarily by email and conference calls, possibly every two weeks, with face-to-face meetings perhaps at each of the OGC TC meetings.
////

=== Supporters of this Charter

The following people support this proposal and are committed to the Charter and projected meeting schedule. These members are known as SWG Founding or Charter members. The charter members agree to the SoW and IPR terms as defined in this charter. The charter members have voting rights beginning the day the SWG is officially formed. Charter Members are shown on the public SWG page. Extend the table as necessary.

|===
|Name             |Organization
|Chris Little     |UK Met Office
|Steve Olson      |US National Weather Service
|Frédéric Guillaud|Météo-France
|===

=== Conveners

Chris Little: Chair, Met Ocean Domain WG

== References

[Weather on the Web Draft Engineering Report](https://github.com/opengeospatial/Weather-on-the-Web-ER) 

OGC WCS Met Ocean Application Profile
