:Title: OGC (Environmental Data Retrieval API SWG Charter)
:titletext: {Title}
:doctype: book
:encoding: utf-8
:lang: en
:toc:
:toc-placement!:
:toclevels: 4
:numbered:
:sectanchors:
:source-highlighter: pygments

<<<
[cols = ">",frame = "none",grid = "none"]
|===
|{set:cellbgcolor:#FFFFFF}
|[big]*Open Geospatial Consortium*
|Submission Date: <2019-08-21>
|Approval Date:   <yyyy-mm-dd>
|Internal reference number of this OGC(R) document:    19-055r0
|Category: OGC(R) Standards Working Group Charter
|Authors:   Chris Little, Steve Olson, Frédéric Guillaud
|===

[cols = "^", frame = "none"]
|===
|[big]*{titletext}*
|===

[cols = "^", frame = "none", grid = "none"]
|===
|*Copyright notice*
|Copyright (C) 2019 Open Geospatial Consortium
|To obtain additional rights of use, visit http://www.opengeospatial.org/legal/
|===

<<<

To: OGC members & interested parties

A new OGC Standards Working Group is being formed. The OGC members listed below have proposed the OGC Environmental Data Retrieval API SWG.  The SWG proposal provided in this document meets the requirements of the OGC Technical Committee (TC) Policies and Procedures.

The SWG name, statement of purpose, scope, list of deliverables, audience, and language specified in the proposal will constitute the SWG's official charter. Technical discussions may occur no sooner than the SWG's first meeting.

This SWG will operate under the OGC IPR Policy. The eligibility requirements for becoming a participant in the SWG at the first meeting (see details below) are that:

* You must be an employee of an OGC member organization or an individual
member of OGC;

* The OGC member must have signed the OGC Membership agreement;

* You must notify the SWG chair of your intent to participate to the first meeting. Members may do so by logging onto the OGC Portal and navigating to the Observer page and clicking on the link for the SWG they wish to join and;

* You must attend meetings of the SWG. The first meeting of this SWG is at the time and date fixed below. Attendance may be by teleconference.

Of course, participants also may join the SWG at any time. The OGC and the SWG welcomes all interested parties.

Non-OGC members who wish to participate may contact us about joining the OGC. In addition, the public may access some of the resources maintained for each SWG: the SWG public description, the SWG Charter, Change Requests, and public comments, which will be linked from the SWG’s page.

Please feel free to forward this announcement to any other appropriate lists. The OGC is an open standards organization; we encourage your feedback.

== Purpose of the Standards Working Group

The Environmental Data Retrieval API Standards Working Group will standardise some APIs, defined with OpenAPI Version 3, to retrieve various common data patterns from a data store. The data patterns will include, but are not restricted to, data at a point in space and time, time series at a point, data along a trajectory, which may be 2, 3, or 4 dimensional, and covering a specified polygon or rectangular tile.  

== Business Value Proposition

Much environmental data is truly 'Big Data', in that it cannot be readily copied and distributed in sensible timescales for many uses. By specifying precisely just the data required in a convenient pattern familiar to the user, a service provider can extract and serve the requested data, simplying access for the user, and hiding the service implementation details, while being scaleable both in terms of the underlying data volumes and the number of supported simultaneous users. 

By using stable, standardised, service APIs based on simple data retrieval patterns, it is envisaged that access and use of data and information will be improved in different domains, including geospatial, facilitating more innovation and value.

It is envisaged that the standard will be consistent with the strategic direction established by "OGC API - Features" and the future OWS Common for Web Services.

The service APIs will support both traditional and cloud-based approaches to computing and also enable a mix of public and private business models on a 'level playing field'. For example, no one country is capable of supplying weather forecast data at the highest useful resolutions for the whole globe, so a distributed scalable approach is essential, enabling both advanced countries and the Least Developed Countries contribute to global strategic initiatives of sustainability and development.

== Scope of Work

The original requirements for this standard were evolved in the Met Ocean Domain Working Group as the Weather on the Web (WotW), but many of the data patterns are applicable in other environmental sciences, or even other domains. The data retrieval patterns to access weather and climate data have been stable for many years. Such patterns include, but are not restricted to, point data, time-series at a point, vertical profiles, trajectories (whether in 2, 3 or 4 dimensions), polygons, or rectangular tiles.

There are two main use cases: 

1. An end user requires some convenient data for a specific, familiar purpose, such as a forecast surface temperature at a point or over an area, or a timeseries of water flow at a river location, or wind speed and direction along a proposed trajectory or route, but the user does not need the full range of data that modern weather or climate predictions, or other Big Data systems, engender.

2. A service provider of many value-added products and information services needs an architecture that decouples the provision of data to many evolving distributed applications from the underlying stable, operational, centralised bulk data production systems. 

The underlying bulk data may be based on regular calculation grids, or may be point-cloud observation based, or other structures.

The service APIs will return the requested data in a specified structured payload format, such as JSON, but not limited to this.

Queries against the service endpoints using the APIs will return all the information that users should need to use the services successfully.

=== Statement of relationship of planned work to the current OGC standards baseline

There is no OGC standard directly addressing these requirements.

It is proposed to use the OpenAPI Version 3 framework to define the APIs, which is consistent with the "OGC API - Features". Previous experiments, proof-of-concepts and prototyping work have confirmed the feasibility of a consistent approach. 

It is planned that once the SWG is established, a candidate standard will be developed within one year.

=== What is Out of Scope?

The SWG will only standardise data retrieval orientated APIs, not product-based APIs that need business specific logic and rules.

Initially, the SWG will not standardise any data patterns other than: point, timeseries, vertical profile, trajectory, corridor, polygon or rectangular tile. 

Initially, the SWG will not standardise data patterns that involve the return of ensemble values or probability distribution functions (the fifth dimension), but envisage that it should be straightforward to generalise to support these use cases.

The SWG will not specify mechanisms for finding data retrieval services and their endpoints.

=== Specific Existing Work Used as Starting Point

The SWG work is based on:

1. The Met Ocean Domain WG work to specify various Best Practices;

2. The WCS Met Ocean Application profiles done in the WCS SWG;

3. The OGC API - Features candidate standard;

4. A Met Ocean DWG Hackathon held in December 2018 in Washington DC, USA;

5. The OGC Hackathon held in June 2019 in London, England, UK;

6. The Weather on the Web API Engineering Report.

=== Is This a Persistent SWG

[x] YES

[ ] NO

=== When can the SWG be Inactivated

As there are several data pattern APIs to be standardised, Persistent SWG status is proposed, but when all the initial deliverables are finished, inactivation will be considered.

== Description of deliverables

A series of APIs will be standardised for different data retrieval patterns. The Met Ocean DWG and other interested parties have already prioritised the patterns at various OGC meetings.

The Met Ocean DWG will also produce a Best Practice document for implementing these APIs within an operational meteorological context.

=== Initial Deliverables

1. API to retrieve data values at a specified location altitude and time (x,y,z,t). Several operational versions of this pattern already exist in different countries for several years.

2. API to retrieve a time series of values at a specified location and height (x,y,z), whether elevation or altitude with a specific vertical CRS. This pattern also has some operational implementations.

3. API to retrieve a vertical profile of values at a specified location and time (x,y,t).

4. API to retrieve an array of values across a rectangular area (tile). Operational immplementation of this pattern has started.

5. API to retrieve a set of values across a polygonal area.

5. API to retrieve a series of values along a specified trajectory, whether 2,3, or 4 dimension.

6. API to retrieve a series of values within a 'corridor', that is, a trajectory with a surrounding buffer region along its length.

=== Additional SWG Tasks

Liaise with the OGC API Features SWG and OWS Common SWG, and other SWGs and DWGs, to ensure consistency of approach to API standardisation.

== IPR Policy for this SWG

[x] RAND-Royalty Free

[ ] RAND for fee

== Anticipated Audience / Participants

Non-expert users of small timely subsets of large data repositories. Use cases vary from rapid, safety-critical environments to research retrievals from long term archives.

Web developers, who are not experts in the characteristics of the data, but have compelling perhaps novel, applications using data from disparate domains.

== Domain Working Group Endorsement

The Met Ocean DWG discussed and endorsed the establishment of this SWG and presented to the OGC Technical Committee in Plenary in Leuven in June 2019.

== Other informative information about the work of this SWG

=== Collaboration

Collaborators are expected to include, beside the Met Ocean DWG: the Hydrology DWG, WFS/FES SWG, OWS Common SWG.

There may be collaboration with the W3C Spatial Data on the Web Interest Group, as it is expected the W3C Best Practices for Data, and Spatial Data, on the Web will be relevant.

There may be the possibility of collaboration with the Research Data Alliance (RDA), and in particular their Data and Metadata Granularity Task Force, part of the Data Discovery Paradigms Interest Group. Granular metadata should be closely related to practical data query patterns.

=== Similar or Applicable Standards Work (OGC and Elsewhere)

The UK Government has mandated the use of OpenAPI Version 3 as a national standard for documenting UK government RESTful APIs. https://www.gov.uk/government/publications/recommended-open-standards-for-government/describing-restful-apis-with-openapi-3 

The Netherlands Government is working towards standardising access to geopsatial data with APIs. https://geonovum.github.io/KP-APIs/#api-designrules 

=== Details of first meeting

An Ad Hoc Working Group meeting will be convened in Banff, September 2019 to discuss and hopefully approve this charter.

An initial teleconference will be organised after Charter adoption, and the first face-to-face meeting will be at the OGC TC Toulouse meeting in November 2019.

=== Projected on-going meeting schedule

There will be face-to-face meetings organised at each OGC Technical Conference. GoToMeeting teleconferences will be arranged, probably fortnightly, between TCs, and the documents will be developed on an OGC public GitHub repository. Email notifications of the issues being discussed will be made available for those unable to access the GitHub.

=== Supporters of this Charter

The following people support this proposal and are committed to the Charter and projected meeting schedule. These members are known as SWG Founding or Charter members. The charter members agree to the SoW and IPR terms as defined in this charter. The charter members have voting rights beginning the day the SWG is officially formed. Charter Members are shown on the public SWG page. Extend the table as necessary.

|===
|Name             |Organization
|Chris Little     |UK Met Office
|Steve Olson      |US National Weather Service
|Frédéric Guillaud|Météo-France
|Dave Blodgett    |US Geological Survey
|Tom Kralidis     |Meteorological Service of Canada
|Roope Tervo      |Finnish Meteorological Institute
|Bruce Bannerman  |
|Chris Lynnes     |NASA
|===

=== Conveners

Chris Little: Chair, Met Ocean Domain WG

== References

Weather on the Web Draft Engineering Report https://github.com/opengeospatial/Weather-on-the-Web-ER

OGC WCS Met Ocean Application Profile

OGC API - Features https://github.com/opengeospatial/WFS_FES
